### ISSUE TITLE
`rbenv shell` no such command

### ISSUE THREAD

**Issue by alessandro-fazzi** [oh-my-fish/plugin-rbenv#12]
This sounds very weird to me, but..

```
 git:(master) 1M$ rbenv shell                                               [ruby 2.2.2]
 rbenv: no such command `shell'
```

anyone experiencing same problem? Other commands seems to work as expected. If I switch to bash the command is recognized as expected.

**Comment by bpinto** [comment]
Does #15 solves this issue for you?

**Comment by alessandro-fazzi** [comment]
Yep, it works! :)
