### ISSUE TITLE
Warning: path component

### ISSUE THREAD

**Issue by mrThe** [oh-my-fish/plugin-rbenv#13]
After update rbenv plugin, i get 

``` bash
set: Warning: path component /usr/local/var/rbenv/bin may not be valid in PATH.
set: No such file or directory
```

when i open new terminal tab.

My fish config:

``` bash
# Path to your oh-my-fish.
set -g OMF_PATH $HOME/.local/share/omf

# Path to your oh-my-fish configuration.
set -g OMF_CONFIG $HOME/.config/omf

# RBENV_ROOT
set -gx RBENV_ROOT /usr/local/var/rbenv

### Configuration required to load oh-my-fish ###
# Note: Only add configurations that are required to be set before oh-my-fish is loaded.
# For common configurations, we advise you to add them to your $OMF_CONFIG/init.fish file or
# to create a custom plugin instead.

# Load oh-my-fish configuration.
source $OMF_PATH/init.fish

# iTerm integration
source ~/.config/fish/.iterm2_shell_integration.fish

. (rbenv init -|psub)
```

Brew output:

``` bash
➜  brew info rbenv
rbenv: stable 0.4.0, HEAD
Ruby environment tool
https://github.com/sstephenson/rbenv
/usr/local/Cellar/rbenv/HEAD (57 files, 256K) *
  Built from source
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/rbenv.rb
==> Dependencies
Recommended: ruby-build ✔
==> Options
--without-ruby-build
    Build without ruby-build support
--HEAD
    Install HEAD version
==> Caveats
To use Homebrew's directories rather than ~/.rbenv add to your profile:
  export RBENV_ROOT=/usr/local/var/rbenv

To enable shims and autocompletion add to your profile:
  if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi
```

Looks like it's about this last commit: https://github.com/oh-my-fish/plugin-rbenv/commit/fc07dfa6a35acb2b3aef6aaba12866543922503b
And i don't have a `bin` folder in `/usr/local/var/rbenv`

**Comment by alessandro-fazzi** [comment]
in your fish config you have

```
# RBENV_ROOT
set -gx RBENV_ROOT /usr/local/var/rbenv
```

Remove it or give it the right path :)

EDIT: you probably copied the code from the "Caveats" section of brew? Anyway if the path doesn't exists you'll have to correct it for sure

**Comment by mrThe** [comment]
@pioneerskies 
I have that path:

``` bash
➜  ll /usr/local/var/rbenv
total 8
drwxr-xr-x  134 mrthe  admin   4.4K Sep 24 14:08 shims
-rw-r--r--    1 mrthe  admin     6B Jul  8  2014 version
drwxr-xr-x   12 mrthe  admin   408B Sep 18 17:35 versions
```

But i don't have `/usr/local/var/rbenv/bin`.

Also, if i remove `set -gx RBENV_ROOT /usr/local/var/rbenv`\- rbenv starts working wrong.

**Comment by alessandro-fazzi** [comment]
Yes, I'm sorry for the mis-reading...
Seems a misinterpretation of the path usage in the commit you spotted; probably it'd be a good idea to ask @Bastes a little help.

**Comment by mrThe** [comment]
Also, let's call author of commit here :)
@bpinto, can you help me with that?

**Comment by Bastes** [comment]
@pioneerskies @mrThe The commit that introduces that regression in your case was meant to fix cases when rbenv is not installed via a package manager like homebrew but under the user's home as a whole package (typically in ~/.rbenv) with the binaries available under the .rbenv/bin dir.

I guess in your case, homebrew insures rbenv is in your path, so there's no need to add $RBENV_ROOT/bin when the rbenv command is already available. I'm sending a PR with a fix right away.

**Comment by Bastes** [comment]
@pioneerskies @mrThe @bpinto [The PR is ready](https://github.com/oh-my-fish/plugin-rbenv/pull/14), but I guess @mrThe should perhaps test it in his environment before merging it, to be safe ^^

**Comment by mrThe** [comment]
@Bastes sure, i can test it. But how can i do it? Where is omf stores plugins?

**Comment by alessandro-fazzi** [comment]
Just FYI and in order to bring some confusion, I've installed rbenv via brew, but I have not the `/usr/local/var/rbenv` dir ... :confused:

**Comment by Bastes** [comment]
@mrThe The rbenv plugin should be located there: $OMF_PATH/pkg/rbenv/ ; you can try by simply pasting the content of my PR's rbenv.fish file ^^

@pioneerskies Well, another occasion to test I'd say ^^ it should work as long as brew installed your rbenv in a directory that's already in your path, I assume.

**Comment by mrThe** [comment]
@Bastes thanks. I just tested your PR, and everything works fine!

**Comment by bpinto** [comment]
Cool! Sorry for not joining the conversation before!

I have merged it, everything should be working now! Thanks for the PR!

**Comment by mrThe** [comment]
Everything works fine now, thanks!
