### ISSUE TITLE
fish: Unknown command 'rbenv'

### ISSUE THREAD

**Issue by arashm** [oh-my-fish/plugin-rbenv#16]
Using the latest version of rbenv I can't seem to make it work on Fish with this plugin installed. I constantly get this error:

```
fish: Unknown command 'rbenv'
~/.local/share/omf/pkg/rbenv/rbenv.fish (line 11):       command rbenv "$command" $argv
                                                                 ^
in function 'rbenv'
    called on standard input
```

running `echo $PATH` gives me:

```
/home/arashm/.rbenv/shims /home/arashm/.nvm/versions/node/v5.3.0/bin /usr/local/sbin /usr/local/bin /usr/bin
```

running `which rbenv` gives me:

```
which: no rbenv in (/home/arashm/.rbenv/shims:/home/arashm/.nvm/versions/node/v5.3.0/bin)
```

`type rbenv` returns:

```
rbenv is a function with definition
function rbenv
    if set -q __RBENV_SUPPORTS_FISH
    command rbenv $argv
  else
    set command $argv[1]
    set -e argv[1]

    switch "$command"
    case rehash shell
      eval (rbenv "sh-$command" $argv)
    case '*'
      command rbenv "$command" $argv
    end
  end
end
```

Still none of the rbenv commands work:

```
⋊> ~ rbenv rehash                                                                                                                                                          15:49:48
fish: Unknown command 'rbenv'
~/.local/share/omf/pkg/rbenv/rbenv.fish (line 11):       command rbenv "$command" $argv
                                                                 ^
in function 'rbenv'
    called on line 26 of file ~/.local/share/omf/pkg/rbenv/rbenv.fish
    with parameter list 'sh-rehash'

in command substitution
    called on line 24 of file ~/.local/share/omf/pkg/rbenv/rbenv.fish

in function 'rbenv'
    called on standard input
    with parameter list 'rehash'
```

**Comment by bpinto** [comment]
`rbenv` is not being found by fish.

This is where I have `rbenv` installed on:

```
$ which rbenv
/usr/local/bin/rbenv
```

Where is yours installed? If it's not already available in your PATH, you need to set it with: `set -gx RBENV_ROOT path_here`

**Comment by arashm** [comment]
Setting the `RBENV_ROOT` didn't help, but adding this solved it:

```
set PATH $HOME/.rbenv/bin $PATH
```

Thank you

**Comment by Bastes** [comment]
Sorry, I'm having something similar (again ^^° #9) on a brand-new ubuntu / fish / omf / rbenv install.

Again, I installed rbenv locally in my user directory (in ```~/.rbenv```).

I tried to add ```set -gx PATH $HOME/.rbenv/bin $PATH``` to my ```~/.config/fish/config.fish```, but apparently the plugin is sourced before ```~/.config/fish/config.fish``` is triggered (I put an echo before the line, the error was reported before the echo).

I tried adding the ```source $OMF_PATH/init.fish``` at the end of ```~/.config/fish/config.fish``` but it sends fish into an infinite loop (The function call stack limit has been exceeded. Do you have an accidental infinite loop?) so I guess the way omf works now has changed.

Have I done something wrong? Does anyone have an idea how I could fix this?
