### ISSUE TITLE
Bug? In rbenv.load

### ISSUE THREAD

**Issue by akemrir** [oh-my-fish/plugin-rbenv#3]
I have strange bug on my fresh install of rbenv plugin.

```
which: no command in (./node_modules/.bin:/home/akemrir/...
```

Error disappears when I comment lines 9 and 10 from rbenv.load. These lines:

```
else if [ (which command; and command command -v rbenv) ]
  set rbenv_binary (command command -v rbenv)
```

How can I fix this?

**Comment by bobthecow** [comment]
Try changing `which command; ...` to `command which command > /dev/null 2>&1; ...`

**Comment by akemrir** [comment]
Ah, yes. Now works like charm.
Thanks for very fast reponse.
