### ISSUE TITLE
Doesn't seem to work on Ubuntu with a user-based root path

### ISSUE THREAD

**Issue by Bastes** [oh-my-fish/plugin-rbenv#9]
Hi,

I'm trying to get the plugin to work on a Ubuntu 15.04 fresh install. I've installed rbenv directly in my user directory (at ~/.rbenv).
It doesn't work out of the box (Please install 'rbenv' first! shows and the rbenv command is unknown).

I tried adding a reference to my rbenv root as suggested in the README in the ~/.config/fish/init.fish file (which didn't exist before this point), which doesn't seem to work either. As the file didn't exist there wasn't any sourcing of oh-my-fish done so I couldn't put it before sourcing omf.

Being of an inquisitive mind, I attempted to add that same line on top of my ~/.config/fish/config.fish file, for no better result.

Being now at my wit's end, I guess I either need to get how to properly do that configuration or report a potential issue with the plugin, hence this post ^^ help to figure out why it doesn't work would be greatly appreciated, and if it leads to discovering why things did go wrong, I'll try to help with a pull request.

Note that rbenv works perfectly well in bash, if it's any help.

**Comment by Bastes** [comment]
Still diagnosing: note that when loading fish from bash, it displays "function fish" instead of the error message when fish starts, and the plugin seems to work, even when I removed the custom rbenv root path from the config files. The problem only arises when fish is started directly in the terminal (after using chsh to set fish as the default shell).

Hope it helps ^^ I'll be trying to use the plugin in bash-born fishes and see wether it works alright.

**Comment by bpinto** [comment]
it doesn't seem like you need to specify the rbenv root. Without the plugin installed, do you have access to rbenv tool on command line?

**Comment by Bastes** [comment]
Thanks for your help ^^d

I tested with and without the plugin installed, the behaviour seems consistant:
- if I start fish from bash, the rbenv command is indeed available, and the shims too ; the $PATH does contain the paths to my ~/.rbenv/bin ~/.rbenv/shims nor ~/.rbenv/plugins/**/bin
- if I start fish as my default shell, the rbenv command is not available ; the $PATH doesn't contain the path to my ~/.rbenv/bin ~/.rbenv/shims nor ~/.rbenv/plugins/**/bin

I thought the plugin was supposed to jumpstart rbenv under fish (executing the eval (rbenv init -) and exporting the path), and so I installed rbenv adding the adequate commands in my .bashrc (to at least have a fallback until fish is properly configured) but I didn't do anything special on fish, assuming the plugin would provide the config (or look in the most common paths to add one where an rbenv command appears).

When that failed, I added the README's " set -gx RBENV_ROOT /home/my-account/.rbenv " to the config files I mentionned earlier without much success. I always added said command line at the top of my config files. When I " echo $RBENV_ROOT " I get the proper path, although it doesn't change my $PATH var.

**Comment by Bastes** [comment]
Another thing to add to the diagnosis: when I run fish from bash without the plugin, my $PATH contains exactly what it contains in bash ; when I run it from bash with the plugin, it adds the /home/my-home/.rbenv/shims before whatever $PATH contains in bash (ironically resulting in my direnv-pushed binstubs being overridden by rbenv's shims).

**Comment by bpinto** [comment]
I cant understand what is happening, could you debug? The plugin code is small, you might be able to find the problem.

**Comment by Bastes** [comment]
Certainly ; I just don't really know where to start actually ^^° I'm a bit new to fish scripting. What would you do in that situation to get better data?

**Comment by Bastes** [comment]
P.S. I don't even know where the plugin code lives. All I see when I explore my  ~/.config/omf directory are a bunch of config files (unsurprisingly), I don't know where else the code could be stored.

**Comment by bobthecow** [comment]
The core library and all installed packages live in `$OMF_PATH` (it's `~/.local/share/omf` by default).

**Comment by Bastes** [comment]
Cool, thanks ^^d I'll see what I can find.

**Comment by Bastes** [comment]
I've already got something fishy (aha).

I added logs to my ~/.config/fish/config.fish and ~/.config/omf/init.fish:

```
# in ~/.config/fish/config.fish
...
echo "~/.config/omf/init.fish SOURCED"
source $OMF_PATH/init.fish
...

# on top of ~/.config/omf/init.fish
echo "~/.config/omf/init.fish BEGIN"
...
```

When fish is the default shell, I'm getting this on startup:

```
~/.config/omf/init.fish SOURCED
Please install 'rbenv' first!
~/.config/omf/init.fish BEGIN
```

So, adding the $RBENV_ROOT declaration in the ~/.config/omf/init.fish is useless, the variable is needed before it loads.

**Comment by bobthecow** [comment]
the line `source $OMF_PATH/init.fish` is sourcing `init.fish` in the core library, not in `~/.config/omf`

**Comment by Bastes** [comment]
Yep, and I guess $OMF_PATH/init.fish in turn sources ~/.config/omf/init.fish, but after sourcing the plugins themselves. So I guess the README for the rbenv plugin should avise to add the $RBENV_ROOT variable setting in the ~/.config/fish/config.fish instead of ~/.config/omf/init.fish?

Now I'm fiddling with rbenv.fish... stay tuna-ed ^^

**Comment by Bastes** [comment]
There, I see what I don't understand.

First, the plugin checks wether rbenv is available in the current path, and exits if not:

```
# rbenv.fish line 5 through 7
if not available rbenv
  echo "Please install 'rbenv' first!"; return 1
end
```

Since my $PATH doesn't contain the path to the rbenv command yet (when fish doesn't inheritate variables from bash), it obviously crashes on me there and then.

What I read next looks like it's sourcing the rbenv init results and setting the paths to the shims and commands when interactive.

So, I'm going to try and add the path to my rbenv command to my fish PATH in ~/.config/fish/config.fish and see how this one sails...

**Comment by Bastes** [comment]
...adding the path to my rbenv command just before sourcing ~/.config/fish/config.fish works a treat.

Do you think I should make a pull request with this added to the README, or that that the plugin needs a fix? My gut feeling tells me that something is missing from the plugin, but I'm not sure my intuition is right here ^^°

**Comment by Bastes** [comment]
(this question is unrelated, but since I'm using direnv to use my projects binstubs, I thought it might be interesting to make a direnv plugin for oh-my-fish ; how do you think should I go about it?)

**Comment by bpinto** [comment]
@bastes the Readme path is wrong indeed. Could you open a PR fixing it? :+1:

@direnv Don't we already have it? :)

**Comment by Bastes** [comment]
@bpinto Sure, coming as soon as I'm on my break ^^

**Comment by Bastes** [comment]
@bpinto I looked into https://github.com/oh-my-fish/ and didn't find a "direnv" repository, so I thought no plugin exists already.

**Comment by bpinto** [comment]
Although we recommend and wish every repository is under the organization, some are not. Try omf install direnv

**Comment by Bastes** [comment]
Oooh, that did work indeed. Cool, thanks ^^

**Comment by Bastes** [comment]
@bpinto Apparently the path in the README was alright when I cloned the repo, so I added a troubleshooting section to explain the plugin needs the rbenv command to be in the path and sent the [pull request #11](https://github.com/oh-my-fish/plugin-rbenv/pull/11) ^^ as far as I'm concerned this issue is closed, thanks for your support ^^
